listen_addresses = '*'
max_connections = 30

shared_buffers = 128MB
effective_cache_size = 512MB
maintenance_work_mem = 64MB
work_mem = 4MB

wal_buffers = 4MB
min_wal_size = 80MB
max_wal_size = 512MB
checkpoint_completion_target = 0.9

random_page_cost = 1.1
effective_io_concurrency = 100

log_destination = 'stderr'
logging_collector = off
log_min_duration_statement = 500ms
log_connections = off
log_disconnections = off

shared_preload_libraries = ''
