ALTER TABLE "JuryMember" ADD COLUMN "team" TEXT NOT NULL DEFAULT 'Júri';
ALTER TABLE "JuryMember" ADD COLUMN "role" TEXT NOT NULL DEFAULT 'TEAM_LEAD';
ALTER TABLE "JuryMember" ADD COLUMN "permissions" TEXT NOT NULL DEFAULT 'OVERVIEW,SUBMISSIONS,VOTES,WINNERS';
