import type { FastifyInstance, FastifyRequest } from "fastify";
import { z } from "zod";
import type { LiveUorStudentAcademicInsights } from "../academics/academic-insights";

const metaSchema = z.object({ traceId: z.string(), product: z.literal("uor_student"), source: z.literal("uor_student") });
function meta(request: FastifyRequest) { return { traceId: request.id, product: "uor_student" as const, source: "uor_student" as const }; }

export async function uorStudentInsightsRoutes(app: FastifyInstance, options: { application: LiveUorStudentAcademicInsights }) {
  app.get("/performance/evolution", { schema: { tags: ["UOR Estudante - Inteligência Académica"], response: { 200: z.object({ data: z.object({ series: z.array(z.object({ snapshotVersion: z.number().int(), average: z.string().nullable(), considered: z.number().int(), missing: z.number().int(), observedAt: z.string(), source: z.literal("secretaria_uor"), stale: z.boolean() })), method: z.string(), coverage: z.enum(["exact", "not_synced"]) }), meta: metaSchema }) } } }, async (request) => ({ data: await options.application.evolution(request.uorStudent!), meta: meta(request) }));
  app.get("/curriculum/completion-estimate", { schema: { tags: ["UOR Estudante - Currículo"], response: { 200: z.object({ data: z.object({ status: z.enum(["estimated", "insufficient_information"]), estimatedRemainingPeriods: z.number().int().nullable(), estimatedCompletion: z.string().nullable(), completedCredits: z.number().nullable(), totalCredits: z.number().nullable(), method: z.string(), assumptions: z.array(z.string()), uncertainty: z.enum(["medium", "high"]), provenance: z.record(z.string(), z.unknown()) }), meta: metaSchema }) } } }, async (request) => ({ data: await options.application.completionEstimate(request.uorStudent!), meta: meta(request) }));
  const provenance = z.object({ source: z.enum(["secretaria_uor", "uor_student"]), observedAt: z.string().nullable(), coverage: z.string(), stale: z.boolean() });
  app.get("/curriculum/map", { schema: { tags: ["UOR Estudante - Currículo"], response: { 200: z.object({ data: z.object({
    items: z.array(z.object({ subjectKey: z.string(), subjectCode: z.string().nullable(), subjectName: z.string(), status: z.enum(["completed", "current", "pending", "failed", "blocked"]), officialStatus: z.string().nullable(), credits: z.number().nullable(), period: z.string().nullable(), prerequisites: z.array(z.string()), source: z.literal("secretaria_uor") })),
    completion: z.object({ completedCredits: z.number().nullable(), totalCredits: z.number().nullable(), percentage: z.number().nullable(), status: z.enum(["official", "not_available"]) }),
    provenance: z.object({ history: provenance, enrollments: provenance, progression: provenance, credits: provenance }),
  }), meta: metaSchema }) } } }, async (request) => ({ data: await options.application.curriculumMap(request.uorStudent!), meta: meta(request) }));
  app.get("/agenda/overload", { schema: { tags: ["UOR Estudante - Agenda"], response: { 200: z.object({ data: z.object({ status: z.literal("advisory"), method: z.string(), threshold: z.object({ events: z.number().int(), hours: z.number() }), periods: z.array(z.object({ weekStartsAt: z.string(), eventCount: z.number().int(), estimatedHours: z.number(), sources: z.array(z.string()) })), recommendation: z.string() }), meta: metaSchema }) } } }, async (request) => ({ data: await options.application.overload(request.uorStudent!), meta: meta(request) }));
  app.get("/agenda/unified", { schema: { tags: ["UOR Estudante - Agenda"], response: { 200: z.object({ data: z.object({ items: z.array(z.object({ id: z.string(), kind: z.enum(["class", "exam", "personal"]), title: z.string(), startsAt: z.string().nullable(), endsAt: z.string().nullable(), location: z.string().nullable(), source: z.enum(["secretaria_uor", "uor_student"]), provenance })), coverage: z.object({ classes: provenance, exams: provenance, personal: provenance }) }), meta: metaSchema }) } } }, async (request) => ({ data: await options.application.agenda(request.uorStudent!), meta: meta(request) }));
  app.get("/agenda/conflicts", { schema: { tags: ["UOR Estudante - Agenda"], response: { 200: z.object({ data: z.object({ status: z.literal("advisory"), method: z.string(), conflicts: z.array(z.object({ leftId: z.string(), rightId: z.string(), leftSource: z.string(), rightSource: z.string(), startsAt: z.string(), endsAt: z.string() })) }), meta: metaSchema }) } } }, async (request) => ({ data: await options.application.conflicts(request.uorStudent!), meta: meta(request) }));
}
